### ISSUE TITLE
ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by HiPhish** [xdissent/jekyll-rst#11]
Hi,

I just tried using your Jekyll plugin, but I get an error about unknown locale.

```
Traceback (most recent call last):
  File "/Users/hiphish/Developer/feeling-responsive/_plugins/jekyll-rst/rst2html.py", line 25, in <module>
    from transform import transform
  File "/Users/hiphish/Developer/feeling-responsive/_plugins/jekyll-rst/transform.py", line 2, in <module>
    from docutils.core import publish_parts
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils/core.py", line 20, in <module>
    from docutils import frontend, io, utils, readers, writers
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils/frontend.py", line 41, in <module>
    import docutils.utils
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils/utils/__init__.py", line 20, in <module>
    import docutils.io
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/docutils/utils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

I have docutils and Pygments installed via pip, otherwise the traceback would not have found them. If I remove the frontmatter from my reST file the error goes away, but it doesn't get compiled obviously. Do you have any idea what is going on?

**Comment by HiPhish** [comment]
This seems to be a general problem with Python on OS X. The solution is to run the following two lines first:

```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

I don't want to run them every time, so I put them in a file called `~/.bash_profile`. Run `source ~/.bash_profile` to get the effect without logging out and back in.

The issue can be closed now, the plugin works.
